language: python
cache: pip
matrix:
  include:
    - python: "3.6"
    - python: "3.7"
    - python: "3.8"
      dist: xenial
      sudo: required

# command to install dependencies
install: "pip install -r requirements.txt"

before_script:
  - pip install flake8
  - pip install black
  - pip install pydocstyle
  # stop the build if there are Python syntax errors or undefined names.
  - flake8 bashplot/ --count --max-line-length=88 --ignore=W293,W291 --statistic
  # stop the build if there are Python syntax follows not the black style.
  - black bashplot/ --check -v
  # exit-zero treats all errors as warnings.
  - flake8 . --count --exit-zero --max-complexity=10 --statistics
  # stop if doc-string is broken in bashplot.
  - pydocstyle bashplot/bashplot.py
  # install bashplot
  - python setup.py install
  # isntall coverage and codecov for report
  - pip install coverage
  - pip install codecov
  # change directory.
  - cd test

# command to run tests
script:
  - coverage run -m unittest test_bashplot.py
  # Generate test coverage report and upload to codecov.io
  - coverage report -m
after_success:
  - codecov

notifications:
  slack:
    on_success: change
    on_failure: always